version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_REVIEW_SERVICE_URL=http://review-service:8080
      - REACT_APP_RESTAURANT_SERVICE_URL=http://restaurant-service:8081
      - REACT_APP_LOGGING_SERVICE_URL=http://logging-service:8082
    networks:
      - app-network2

networks:
  app-network2:
    external:
      name: n11-final-network
